### ISSUE TITLE
Bug with font

### ISSUE THREAD

**Issue by Xstoudi** [BoostIO/boost-app-discussions#49]
Hey !
When I try to change the editor's font, it's been a shift.
I try to use "Roboto" font.
![Nope](http://i.imgur.com/AJCAz6J.gif)

**Comment by Rokt33r** [comment]
It's not a bug. You should use a Monospace font in this case.
> Of course, It's good to use Roboto for the font of Markdown preview

This is because, [Ace editor](http://ace.c9.io)(Currently using) is trying to render letters and characters(even Chinese, Japanese and also Korean characters) with the same amount of horizontal space. This increases the readability of source code.

Try [Roboto Mono](https://www.google.com/fonts/specimen/Roboto+Mono) instead of Roboto.
