### ISSUE TITLE
About Opensource(We need your opinion!)

### ISSUE THREAD

**Issue by Rokt33r** [BoostIO/boost-app-discussions#62]
## Check the link below.

https://github.com/BoostIO/Boostnote

~~# We've decided to release this app as GPL-3.0 after two weeks.~~

>
~~We want to ask you for advice.~~
~~My team think opensourcing this app would be great. But, before execute it, We have to listen to your opinion.~~
### ~~If Boostnote is opensourced, What will you do??~~
~~Please give your opinion. Thanks.~~

**Comment by Rokt33r** [comment]
@ykicisk @hiroyuki-sato @alexanderadam @javihernandez @alemonmk @germanocorrea 
Please check this issue and give me your opinion if you don't mind. :pray:

**Comment by germanocorrea** [comment]
There are a lot of reasons I could explain why a free software is important. But, I should warn that, if you want to earn money with this app and open its source code, you should think why people should use your app, instead of an app based on your source code. It could be something like a service, which only you could provide, or something like that.

Instead, if the app's cost is completly free, there's no reason why you should keep it closed source. Then you can have a look at which license fits you best. For exemple, MIT keeps the code open, free for use, modification and distribution, but you can sublicense it (and close de source of your distribution, for exemple - and that's why I don't like this one). GPL it's like MIT, but you can't sublicense it (so, if I modify the app, I need to distribute it under GPL). There are many others, like Mozzila Public License (which you need to change de software name if you want to distribute a modification, just like Firefox), BSD License and Apache Public License. I won't say which one is the best, because you need to understand each one of those licenses to better choose which one fits best the app.

I read on your website (https://b00st.io/) that soon is coming premium plans. If you open the source code, you should know a way to people prefere your app instead of another fork with the same features as the premium, but free. That's something to think about.

Anything I develop, if it's possible, I release it under some FOSS license, because I believe that's the best for society (even if I don't develop too much, I'm still studying). Free Software guarantees that the users can't trust the software, and the same doesn't have malware or something like that, beacause they can look at the source; Free Software also instigates colaborativism, since you have a community helping in the development; and, yet, people can learn how to code by just analysing the source code. Free Software becames a contribution to society, if it's something really useful.

These are just a few reasons why I believe Free Software is great, and why I think every single software should be free as in freedom.

Sorry for my poor english, isn't my mother language - I'm brazilian - and I'm writing fast beacause I'm late.

**Comment by Rokt33r** [comment]
@germanocorrea Thanks for your comment. It is so helpful.:beers:
> The question has been slightly modified after your commenting. But, it's okay to ignore it.

**Comment by ykicisk** [comment]
OSS化については、個人的には嬉しい知らせです。

> Why Boostnote should be Opensourced?　

長所として、

* 他人のcontributionが期待できる(bugfix, new feature, ...)
* ユーザが安心して使える
* OSSというステータスを得る

ということがあるかと思います。

短所としては、マネタイズが難しくなることが挙げられますが、フリープラン部分のソースのみを公開するなど、いくつか方法があると思います。

> If Boostnote is opensourced, What will you do??

今まで自分が立てた（将来立てる）Issueについて、何かしらお手伝いできるかもしれません。

**Comment by dojineko** [comment]
OSS化素敵です :+1: 
@ykicisk さんの挙げられているメリット、デメリットに同意します。

> If Boostnote is opensourced, What will you do??

自分の手元のメモをboostnoteに移した兼ね合いもあり、
気がついたところで機能改善のお手伝いができたらいいなぁと思っております。

**Comment by javihernandez** [comment]
> We want to ask you for advice.
> 
> My team think opensourcing this app would be great. But, before execute it, We have to listen to your opinion.
> 
> Why Boostnote should be Opensourced?

I'd say that this is up to you, the Boostnote team. As @germanocorrea has said, you need to know how do you want to make profit from Boostnote. Either with a pro version of the app with special features or pricing plans, services, etc.

> 
> If Boostnote is opensourced, What will you do??
> 

If you're familiar with open source communities, you already know that by having the source code available, any user can help you to improve/fix your application as others have said in their comments. As an example, if boostnote was open sourced I'd probably try to:

- Not only report bugs as I find them but even trying to fix them
- Help with new features, ie: make it work on linux.

> Please give your opinion. Thanks.

**Comment by Rokt33r** [comment]
@germanocorrea @ykicisk @dojineko @javihernandez 
My team had discussed about this for quite long time.
We've reached the conclusion almost. So, I think I can bring the good news about OSS on this Thursday.
(Currently, I am not in Japan and off work awhile for personal reason. After that day, I'll start dedicating myself to develop this project.)

I really appreciate you all and hope you to wait a little more.

**Comment by hiroyuki-sato** [comment]
あんまりまとまっていませんが、、ちょっと考えたので結論が出る前に書いておきます。

## ソースが公開されることについて

学生の人がGitHubに作ったソースを公開していれば、ソフトウェア業界に就職する際の履歴書になります。
(事実githubのアカウントを教えて欲しいという企業は増えているように思います。)

逆に、就職する側からみれば、就職しようか考えている企業がどんなプログラムを書いているかを知ることができると思います。


企業として考えた場合、ソースをオープンにしているホットな企業の一つがトレジャーデータだと思っています。
https://thinkit.co.jp/story/2015/07/17/6232

上記文書にあるコミュニティを育てるということは、いいと思うんですがBoostnoteがでどうマネタイズするか？？という問題がついてまわりますね。

一般利用者からしたらソースが公開されたらいざとなったら自分で直せるというメリットがあると思います。

## 実際ソースが公開されたら

実際に修正したり、プルリクエストを出したりするかは能力の問題もありますが、やっぱり、開発した人のモチベーションが高くて、
更新が頻繁だったり、Issueに回答したりというコミュニティ活動が活発な場合に、応援(PR出したり)しようかなと思うことが多いような気がします。

**Comment by Rokt33r** [comment]
@hiroyuki-sato 意見ありがとうございます！

**Comment by Rokt33r** [comment]
My team want to delay to make the decisions on this Saturday.
I'm really sorry for our hesitating.
This project is not my own thing. So, I want my team to fully understand...

**Comment by gromain** [comment]
Open sourcing will also allow you to have help from your users for developing new features (say hi to linux over there!) which I think is also very important!

**Comment by Rokt33r** [comment]
We've decided to release this app as `GPL-3.0` after two weeks.
Thanks for your opinions. And feel free to ask if you have some questions about this.

**Comment by dojineko** [comment]
OSS化決定 嬉しいニュースです！２週間後が楽しみです。 :tada: 

少し蛇足になりますが、 MITやBSDでなく、あえてGPLv3を選択した経緯や理由など、
もし可能でしたらお聞かせいただきたいです。 @Rokt33r

**Comment by Rokt33r** [comment]
@dojineko 
チームで話した内容では、アプリのコードの利用がアプリの改善に繋がるように流れを作りたい気持ちがあった感じですね。

GPLv3が正しい選択であるのかは確信がないですけど、一応これで状況を見たい感じです！

**Comment by dojineko** [comment]
@Rokt33r 
GPLv3のコピーレフトが良い方向に作用するように と言った感じでしょうか
なるほどです！ありがとうございますー :bow:

**Comment by germanocorrea** [comment]
Great news :D

**Comment by Rokt33r** [comment]
The repository has been published as OSS. @germanocorrea @dojineko @gromain @hiroyuki-sato @javihernandez @ykicisk 

https://github.com/BoostIO/Boostnote

**Comment by germanocorrea** [comment]
nice :smile:
