### ISSUE TITLE
boost hangs after update to 0.4.2

### ISSUE THREAD

**Issue by laher** [BoostIO/boost-app-discussions#9]
Boost is hanging for me since updating.

 * I only just started using boost 2 days ago.
 * I accepted an update to v0.4.2
 * Now it just hangs on "Loading ...".
 * I tried rebooting, etc.
 * I use a MacBook Pro (2014, El Capitan)

 Now my notes are stuck inside boost. What can I do?

Thanks

**Comment by Rokt33r** [comment]
I've changed the storage of the notes to `~/Library/Application Support/boost/local.json` since v0.4.2. (Formerly notes had been saved in `localStorage`.)
I think my app failed to write `local.json` file(or to read). Could you find it?

And could you download Boost again? (It's fine because `localStorage` is also in `~/Library/Application Support/boost` folder)

**Comment by Rokt33r** [comment]
Issue closed: Boost has been updated to v0.4.3! (2015/12/1)
